package com.example.hp15series.myapps;

import java.util.ArrayList;

public class datawisata{
    public static String[][] data = new String[][]{
            {"Jember", "Pantai Tanjung Papuma", "Jika jalan-jalan ke Jember jangan lupa sempatkan waktu sejenak untuk menikmati eksotisme Pantai Tanjung Papuma yang belum banyak diketahui orang ini. Keindahan pantai dengan pasir putihnya yang masih bersih, ombaknya hingga  suasana alamnya yang begitu menentramkan memberikan pengalaman yang luar biasa ketika menghabiskan waktu di sini.\n" +
                    "\n" +
                    "Dan lagi banyak aktivitas seru yang bisa Anda lakukan untuk menghabiskan waktu di sini, dari berenang di pantai hingga diving untuk mengeksplor keindahan terumbu karangnya. Anda pun juga bisa menyewa perahu untuk menemukan spot diving yang keren.\n" +
                    "\n" +
                    "Hal yang membuatnya tak begitu diminati hanyalah akses jalan yang belum bersahabat sehingga tak banyak yang mau bersusah payah menuju pantai cantik di pesisir kota Jember ini. Seperti tempat wisata di Jember lainnya, destinasi ini pun juga sudah dilengkapi dengan fasilitas kebersihan hingga villa yang bisa disewa jika Anda ingin menikmati malam yang syahdu disini.", "https://www.nativeindonesia.com/wp-content/uploads/2019/04/Tanjung-Papuma.jpg","https://www.google.co.id/maps/place/Pantai+Papuma/@-8.4310054,113.5515929,16z/data=!3m1!4b1!4m5!3m4!1s0x2dd682a6a4b5cd8d:0xb9c242f3a09e2d2e!8m2!3d-8.4300871!4d113.5536464"},
            {"Jember", "Teluk Love", "Ingin menikmati wisata kekinian yang hits banget di Jember? Kalau begitu jangan lewatkan untuk mampir ke Teluk Love. Disebut demikian karena teluk tersebut memiliki bentuk yang tak biasa dan jika dilihat dari kejauhan nampak seperti ikon cinta. Tak heran jika tempat wisata di Jember ini langsung diminati banyak orang yang penasaran dengan keindahannya.\n" +
                    "\n" +
                    "Seperti kebanyakan pantai di pesisir selatan pulau Jawa, teluk ini juga memiliki ombak yang besar jadi harus ekstra waspada jika ingin menjelajahinya lebih dekat.", "https://www.nativeindonesia.com/wp-content/uploads/2019/04/teluk-love.jpg","https://www.google.co.id/maps/place/Teluk+Love/@-8.4408415,113.5870392,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6942520c45715:0x3cabb1f5dd90a01b!8m2!3d-8.4408415!4d113.5892279"},
            {"Jember", "Puncak B29", "Kontur wilayahnya yang dilalui barisan pegunungan membuat Jember memiliki alam yang memukau. Salah satunya ialah Puncak B29 yang akan menyajikan kerennya landskap kota Jember, juga Gunung Argopuro  di lain sisi serta Gunung Raung yang mempesona dari atas ketinggian.\n" +
                    "\n" +
                    "Meskipun jarak dan akses jalan yang menantang, tetapi dengan pesona yang ditawarkan akan membuat siapapun tak akan kecewa. Terutama buat penggemar traveling dan pemburu spot foto instagramable, tempat ini layak jadi destinasi wisata yang wajib dikunjungi. Terutama ketika menunggu matahari tenggelam, sungguh fenomena yang tak boleh disia-siakan.", "https://www.nativeindonesia.com/wp-content/uploads/2019/04/puncak-89.jpg","https://www.google.co.id/maps/place/Puncak+B29/@-7.9592318,112.9926447,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd647e555555555:0x5cf5334088ce710e!8m2!3d-7.9592318!4d112.9948334"},
            {"Jember", "Air Terjun Tancak", "Bagaikan oase di tengah belantara, Air Terjun Tancak menyuguhkan pesona alam yang memukau dan akan memanjakan setiap mata yang memandangnya. Letaknya yang berada di area pegunungan Argopuro dengan akses yang kurang mendukung membuat tempat wisata di Jember ini seolah tersembunyi dibalik kecantikannya.\n" +
                    "\n" +
                    "Dengan ketinggian tebing hingga 82 meter serta debit air hingga 150 m3 per detik, air terjun  tampak begitu memukau. Dan lagi lintasan pendakian yang cukup aman membuat tempat ini layak dikunjunginterutama bagi pecinta traveling.", "https://www.nativeindonesia.com/wp-content/uploads/2019/04/Air-Terjun-Tancak.jpg","https://www.google.co.id/maps/place/Air+Terjun+Tancak/@-8.0648772,113.6167616,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6edaa995f359d:0x7f2c804aeecf2dda!8m2!3d-8.0648772!4d113.6189503"},
            {"Jember", "Pantai Watu Ulo", "Pantai ini dinamakan sebagai Pantai Watu Ulo karena ada sebagian daratan yang menjorok ke laut dengan tekstur batuan yang terlihat seperti badan seekor ular. Tak heran jika warga menyebutnya dengan sebutan Watu Ulo (Batu Ular). Tarif retribusi untuk masuk ke pantai ini sekitar 10 ribu rupiah saja. Jarak dari pusat kota hanya 40 kilometer yang dapat ditempuh selama 45 menit.", "https://cdn0-production-images-kly.akamaized.net/stb6XbNSU8AsjUon6tcnEHZ4ehY=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2757619/original/071410700_1553161128-Pantai_Watu_Ulo__Sumber_iStock_.jpg","https://www.google.co.id/maps/place/Pantai+Watu+Ulo/@-8.4281779,113.5464437,14z/data=!4m8!1m2!2m1!1swatu+ulo!3m4!1s0x2dd69d2fffffffff:0x6f3d7097accf3209!8m2!3d-8.425297!4d113.561897"},
            {"Jember", "Kebun Teh Gunung Gambir", "Jika kamu sudah puas menikmati asupan vitamin sea alias pantai di Jember, kamu bisa berkunjung ke Kebun Teh Gunung Gambir. Di sana, kamu bisa melihat hamparan perkebunan teh yang memukau dengan seri warna hijaunya yang asri.\n" +
                    "\n" +
                    "Kamu bisa sekadar berjalan-jalan menikmati sejuknya udara di Kebun Teh Gunung Gambir sambil sesekali berswafoto bersama keluarga atau sahabat. Banyak spot eksotik yang tidak boleh kamu lewatkan jika berkunjung ke kebun teh di Jember ini.", "https://cdn1-production-images-kly.akamaized.net/Ra6rHoWg_iuJT_4OLMQjrM3xw64=/1280x720/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1475839/original/099110800_1484719852-13.jpg","https://www.google.co.id/maps/place/Pondok+Pesona+Kebun+Teh+Gambir/@-8.03494,113.4391713,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6f682b6ddccbb:0x3255b453115ffe8f!8m2!3d-8.03494!4d113.44136"},
            {"Jember", "Pantai Puger", "Tempat wisata di jember selanjutnya adalah pantai puger yang tak pernah sepi akan pengunjung. Di pantai ini anda bisa menikmatinya ini dengan cara memancing. Bagi anda yang ingin membeli ikan segar dengan harga murah, di tempat ini juga terdapat pelelangan ikan.", "https://wisatapro.com/wp-content/uploads/2016/11/pantai-puger.jpg","https://www.google.co.id/maps/place/Pantai+Puger/@-8.3817964,113.4310803,14z/data=!3m1!4b1!4m5!3m4!1s0x2dd68115efe221cf:0x6665d9208163cbe7!8m2!3d-8.3778522!4d113.4473849"},
            {"Jember", "Air Terjun Sumber Salak", "Air Terjun yang satu ini cukup unik, karena memiliki dua tingkatan, yaitu aliran atas dan aliran bawah. Air terjun dengan air yang jernih ini terletak di Desa Sumbersalak, Ledokombo. Untuk menuju ke tempat wisata di Jember terbaru ini, wisatawan harus melewati jalanan terjal dan melelahkan. Air terjun ini sangat cocok dikunjungi oleh kalian yang memiliki jiwa petualang.", "https://tempatwisataindonesia.id/wp-content/uploads/2017/07/Air-Terjun-Sumber-Salak-Jember.jpg","https://www.google.co.id/maps/place/Air+Terjun+Anjasmoro+Sumbersalak/@-8.1649149,113.8956594,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6b9649c66022b:0xa98b1c71f719103!8m2!3d-8.1649149!4d113.8978481"},
            {"Jember", "Air Terjun Tancak Tulis", "Air Terjun ini terkenal dengan julukan “air terjun dari langi” karena memiliki tinggi aliran sekitar 250 meter, bahkan puncak aliran sering tertutup kabut. Hal ini menjadikan Air Terjun Tancak sebagai salah satu air terjun tertinggi di Jawa Timur. Untuk menuju air terjun ini, para wisatawan harus berjalan kaki menyusuri jalan setapak sejauh kurang lebih 3 Km. Wisata yang ada di Jember ini berlokasi di Dusun Tulis, Desa Darungan, Kecamatan Tanggul, Jember.", "https://tempatwisataindonesia.id/wp-content/uploads/2017/07/Air-Terjun-Tancak-Tulis-Jember.jpg","https://www.google.co.id/maps/place/Tancak+Tulis/@-8.0643584,113.543855,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6f2e155555555:0x28cf4f02ed5941a1!8m2!3d-8.0643584!4d113.5460437"},
            {"Jember", "Rembangan", "Wisata Rembangan Jember adalah sebuah wisata yang berlokasi di sebuah puncak pegunungan yang menonjolkan agrowisata. Secara garis besar, ada dua objek wisata yang ditawarkan, yaitu pemandian dan pemandangan puncak.", "https://1.bp.blogspot.com/-C6z6Ccwlfuc/VrU8o3I3RPI/AAAAAAAABFk/xtfkRV1J5M4/s1600/Wisata+Pemandian+Rembangan.jpg","https://www.google.co.id/maps/place/Puncak+Rembangan/@-8.0785502,113.6882796,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd6eb6b22b4390b:0xcdcfa9792af9847c!8m2!3d-8.0785502!4d113.6904683"},
    };
    public static ArrayList<wisata> getListData(){
        ArrayList<wisata> list = new ArrayList<>();
        for (String[] aData : data) {
            wisata Wisata = new wisata();
            Wisata.setKota(aData[0]);
            Wisata.setJudul(aData[1]);
            Wisata.setDeskripsi(aData[2]);
            Wisata.setFoto(aData[3]);
            Wisata.setMaps(aData[4]);
            list.add(Wisata);
        }
        return list;
    }
}